name:                abs
version:             0.1.0.0
github:              "toyboot4e/abs-hs"
license:             MIT
author:              "toyboot4e"
maintainer:          "toyboot4e@gmail.com"
copyright:           "2022 toyboot4e"

extra-source-files:
- README.adoc

# synopsis:            Short description of your package
# category:            Web
description:         Atcoder begginers selection in Haskell

dependencies:
- base >= 4.7 && < 5

# library:
#   source-dirs: src

# DRY for package.yaml executables:
# <https://www.reddit.com/r/haskell/comments/haeqin/dry_for_packageyaml_executables/>
_exe-defs: &exe-defaults
  source-dirs: app
  # dependencies:
  # - abs
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  other-modules: []

executables:
  P01-exe:
    <<: *exe-defaults
    main:                P01.hs

  P02-exe:
    <<: *exe-defaults
    main:                P02.hs

  P03-exe:
    <<: *exe-defaults
    main:                P03.hs

  P04-exe:
    <<: *exe-defaults
    main:                P04.hs

  P05-exe:
    <<: *exe-defaults
    main:                P05.hs

  P06-exe:
    <<: *exe-defaults
    main:                P06.hs

  P07-exe:
    <<: *exe-defaults
    main:                P07.hs

  P08-exe:
    <<: *exe-defaults
    main:                P08.hs

# # TODO: Use it or remove it
# tests:
#   abs-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - abs
